[package]
name = "rust_code"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
plotters = "0.3"
meval = "0.2"          # For parsing math expressions
csv = "1.3"